// import React from 'react';

// const PrivacyPolicy = () => {
//   return (
//     <div className="privacy-policy-container">
//       <h1>Privacy Policy for Namekart-CRM</h1>
//       <p>Last updated: June 18, 2024</p>
//       <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
//       <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>
//       <h2>Interpretation and Definitions</h2>
//       <h3>Interpretation</h3>
//       <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
//       <h3>Definitions</h3>
//       <p>For the purposes of this Privacy Policy:</p>
//       <ul>
//         <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
//         <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
//         <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Namekart Pvt Ltd, sector-50, Noida.</li>
//         <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
//         <li><strong>Country</strong> refers to: Uttar Pradesh, India</li>
//         <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
//         <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
//         <li><strong>Service</strong> refers to the Website.</li>
//         <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
//         <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
//         <li><strong>Website</strong> refers to Namekart-CRM, accessible from https://app.namekart.com/crm</li>
//         <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
//       </ul>
//       <h2>Collecting and Using Your Personal Data</h2>
//       <h3>Types of Data Collected</h3>
//       <h4>Personal Data</h4>
//       <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
//       <ul>
//         <li>Email address</li>
//         <li>Usage Data</li>
//       </ul>
//       <h4>Usage Data</h4>
//       <p>Usage Data is collected automatically when using the Service.</p>
//       <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
//       <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
//       <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
//       <h3>Tracking Technologies and Cookies</h3>
//       <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
//       <ul>
//         <li>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
//         <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
//       </ul>
//       <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
//       <ul>
//         <li><strong>Necessary / Essential Cookies</strong><br />
//         Type: Session Cookies<br />
//         Administered by: Us<br />
//         Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
//         <li><strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
//         Type: Persistent Cookies<br />
//         Administered by: Us<br />
//         Purpose: These Cookies identify if users have accepted the use of cookies on the         opted the use of cookies on the Website.</li>
//         <li><strong>Functionality Cookies</strong><br />
//         Type: Persistent Cookies<br />
//         Administered by: Us<br />
//         Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
//       </ul>
//       <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
//       <h3>Use of Your Personal Data</h3>
//       <p>The Company may use Personal Data for the following purposes:</p>
//       <ul>
//         <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
//         <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
//         <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
//         <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
//         <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
//         <li>To manage Your requests: To attend and manage Your requests to Us.</li>
//         <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
//         <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
//       </ul>
//       <p>We may share Your personal information in the following situations:</p>
//       <ul>
//         <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
//         <li>For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
//         <li>With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
//         <li>With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
//         <li>With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
//         <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
//       </ul>
//       <h3>Retention of Your Personal Data</h3>
//       <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
//       <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
//       <h3>Transfer of Your Personal Data</h3>
//       <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
//       <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
//       <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
//       <h3>Delete Your Personal Data</h3>
//       <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
//       <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
//       <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
//       <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
//       <h3>Disclosure of Your Personal Data</h3>
//       <p>Business Transactions: If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
//       <p>Law enforcement: Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
//       <p>Other legal requirements: The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
//       <ul>
//         <li>Comply with a legal obligation</li>
//         <li>Protect and defend the rights or property of the Company</li>
//         <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
//         <li>Protect the personal safety of Users of the Service or the public</li>
//         <li>Protect against legal liability</li>
//       </ul>
//       <h3>Security of Your Personal Data</h3>
//       <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
//       <h3>Children's Privacy</h3>
//       <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
//       <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
//       <h3>Links to Other Websites</h3>
//       <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
//       <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
//       <h3>Changes to this Privacy Policy</h3>
//       <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
//       <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
//       <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
//       <h3>Contact Us</h3>
//       <p>If you have any questions about this Privacy Policy, You can contact us:</p>
//       <ul>
//         <li>By email: tech@namekart.com</li>
//       </ul>
      
//     </div>
//   );
// };

// export default PrivacyPolicy;

import React from 'react';

const styles = {
  body: {
    fontFamily: 'Arial, sans-serif',
    lineHeight: '1.6',
    margin: '0',
    padding: '30px',
    // backgroundColor: '#f4f4f4',
  },
  h1: {
    color: '#333',
    fontSize: '2.5em',
  },
  h2: {
    color: '#333',
    fontSize: '2em',
    marginTop: '40px',
  },
  h3: {
    color: '#333',
    fontSize: '1.5em',
    marginTop: '30px',
  },
  p: {
    marginBottom: '20px',
  },
  ul: {
    listStyleType: 'disc',
    marginLeft: '40px',
    marginBottom: '20px',
  },
  ol: {
    marginLeft: '40px',
  },
  a: {
    color: '#1a73e8',
    textDecoration: 'none',
  },
  aHover: {
    textDecoration: 'underline',
  }
};

const PrivacyPolicy = () => (
  <div style={styles.body}>
    <h1 style={styles.h1}>Privacy Policy</h1>

    <p><strong>Effective Date:</strong> July 19, 2024</p>

    <p>
      Namekart Private Limited ("we," "our," or "us") is committed to protecting the privacy of our employees who use our Customer Relationship Management (CRM) website ("Service"). This Privacy Policy explains how we collect, use, and safeguard your information when you use our Service, including the sensitive use of Google Mail services for email campaigns.
    </p>

    <h2 style={styles.h2}>Table of Contents</h2>
    <ol style={styles.ol}>
      <li><a href="#statement" style={styles.a}>What This Statement Covers</a></li>
      <li><a href="#personal-information" style={styles.a}>Personal Information We Collect</a></li>
      <li><a href="#content" style={styles.a}>Content or Information You Provide in the Services</a></li>
      <li><a href="#use" style={styles.a}>How We Use Personal Information We Collect</a></li>
      <li><a href="#share" style={styles.a}>How We Share Personal Information</a></li>
      <li><a href="#choices" style={styles.a}>Your Choices - Opting Out, Correcting, or Accessing Your Information</a></li>
      <li><a href="#security" style={styles.a}>Data Security and Data Transfers</a></li>
      <li><a href="#dispute" style={styles.a}>Dispute Resolution</a></li>
      <li><a href="#changes" style={styles.a}>Notice of Changes</a></li>
      <li><a href="#contact" style={styles.a}>Contacting Namekart</a></li>
    </ol>

    <h3 id="statement" style={styles.h3}>1. What This Statement Covers</h3>
    <p style={styles.p}>
      This Privacy Policy describes the types of information we may collect from you or that you may provide on the app.namekart.com/crm website ("Website" or "Service") and its related products and services (collectively, "Services"). It details our practices for collecting, using, maintaining, protecting, and disclosing your Personal Information, and your choices regarding this information.
    </p>

    <p style={styles.p}>
      Our Services are intended for internal use by Namekart Private Limited employees for bulk mailing to customers and are not directed at children under the age of 16. We do not knowingly collect information from individuals under this age. If you are under 16, please do not use the Services or provide any information to us. It is our firm commitment to protect the privacy of children and comply with relevant regulations such as the Children's Online Privacy Protection Act (COPPA).
    </p>

    <p style={styles.p}>
      We may update this Privacy Policy periodically. Updates will be posted on this page with the date of the most recent revision. Significant changes will be communicated through the Service, via pop-ups, emails, or other reasonable methods. This ensures that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it.
    </p>

    <p style={styles.p}>
      By using our Services, you agree to the collection and use of your information in accordance with this Privacy Policy. If you do not agree with the terms set forth in this Privacy Policy, please do not use our Services. Your continued use of the Services following the posting of changes to this Privacy Policy will mean that you accept those changes.
    </p>

    <h3 id="personal-information" style={styles.h3}>2. Personal Information We Collect</h3>
    <p style={styles.p}>We may collect and process the following types of information:</p>

    <p style={styles.p}>
      <strong>Personal Information:</strong> When you register and log in to the Service, we collect your email address and password. This information is necessary to create and manage your account, ensure secure access, and provide personalized services. Additionally, we may collect your name, job title, and other profile information that you choose to provide. This helps us customize your experience and provide better support and services. Personal information also includes any communications you have with us, such as emails or phone calls, which we use to ensure quality service and resolve any issues you may encounter.
    </p>

    <p style={styles.p}>
      <strong>Email Campaign Data:</strong> To facilitate bulk mailing, you may register additional email IDs. We collect and store the associated access tokens and refresh tokens necessary for Gmail service integration. This allows us to send emails on your behalf through the Gmail service. The collection of these tokens is essential for maintaining the functionality and security of our email campaigns. By integrating with Gmail, we can ensure that your emails are sent reliably and securely, leveraging the advanced features and infrastructure provided by Google Mail services.
    </p>

    <p style={styles.p}>
      <strong>Usage Data:</strong> We may collect information about how you use the Service, including the frequency and duration of your activities. This data helps us understand how the Service is used and identify areas for improvement. Usage data can include information about your interactions with the Service, such as pages visited, features used, and links clicked. This helps us optimize the Service and enhance your user experience. By analyzing usage patterns, we can identify which features are most popular and which may need enhancement, ensuring that we continue to meet your needs effectively.
    </p>

    <p style={styles.p}>
      <strong>Information You Provide Through Support Channels or Communities:</strong> You may provide information or content to us through customer support, including interactions with our support team or community forums. This can include details about your inquiries, feedback, and any issues you encounter. This information is used to resolve your concerns and improve our Services. By gathering feedback and understanding the challenges you face, we can make necessary adjustments and improvements to the Service, ensuring that it remains user-friendly and effective.
    </p>

    <h3 id="content" style={styles.h3}>3. Content or Information You Provide in the Services</h3>
    <p style={styles.p}>When you create an account or use our Service, you may provide various types of content or information, including:</p>

    <ul style={styles.ul}>
      <li>
        <strong>Registration Information:</strong> When you register for an account, you provide us with your email address and password. This information is essential for account creation, authentication, and security. Ensuring that your account is secure is our top priority, and collecting this information allows us to protect your data and provide you with a safe experience.
      </li>
      <li>
        <strong>Profile Information:</strong> Information you add to your user profile, such as your name, job title, and contact details. This helps us personalize your experience and provide relevant content and services. By knowing more about you, we can tailor our Services to better meet your needs and preferences.
      </li>
      <li>
        <strong>Campaign Data:</strong> Information related to your email campaigns, including email addresses, content, and schedules. This data is crucial for managing and executing your email campaigns effectively. By understanding the specifics of your campaigns, we can help you achieve better results and streamline your email marketing efforts.
      </li>
    </ul>

    <p style={styles.p}>
      Providing accurate and up-to-date information is important for the functionality of the Service. Please ensure that the information you provide is accurate and kept up to date. You can update your profile information at any time through the Service interface or by contacting us directly. Keeping your information current helps us provide you with the best possible service and ensures that you receive important updates and notifications.
    </p>

    <h3 id="use" style={styles.h3}>4. How We Use Personal Information We Collect</h3>
    <p style={styles.p}>We use the information we collect for various purposes, including:</p>

    <ul style={styles.ul}>
      <li>
        <strong>To Provide and Support the Services:</strong> We use your personal information to provide, operate, and maintain our Service, including account management and email campaign facilitation. This ensures that you have access to the features and functionalities of the Service. By leveraging your personal information, we can deliver a seamless and efficient experience, helping you achieve your goals with minimal effort.
      </li>
      <li>
        <strong>To Improve Our Services:</strong> We analyze usage data to understand how our Service is used and to make improvements. This helps us optimize the user experience and introduce new features that enhance the Service. By continuously refining and enhancing our Service, we can provide you with a better experience and ensure that we meet your evolving needs.
      </li>
      <li>
        <strong>To Communicate With You:</strong> We use your contact information to send you important updates, respond to your inquiries, and provide customer support. Keeping you informed about changes to our Service or responding to your questions is essential for maintaining a positive relationship. Effective communication allows us to address your concerns promptly and keep you informed about important developments.
      </li>
      <li>
        <strong>To Enforce Our Policies and Comply With Legal Obligations:</strong> We may use your information to enforce our terms of service, protect our rights, and comply with legal obligations. Ensuring that our Service is used in accordance with our policies and legal requirements is crucial for maintaining a safe and secure environment. By enforcing our policies, we can protect both your interests and ours, ensuring a fair and transparent service.
      </li>
    </ul>

    <h3 id="share" style={styles.h3}>5. How We Share Personal Information</h3>
    <p style={styles.p}>We do not sell your personal information to third parties. We may share your information in the following circumstances:</p>

    <ul style={styles.ul}>
      <li>
        <strong>With Service Providers:</strong> We may share your information with third-party service providers who perform services on our behalf, such as email delivery and data storage. These providers are contractually obligated to protect your information and use it only for the purposes specified by us. By working with trusted service providers, we can enhance the quality and reliability of our Service while ensuring that your information remains secure.
      </li>
      <li>
        <strong>For Legal Reasons:</strong> We may disclose your information if required to do so by law or in response to valid requests by public authorities, such as a court or government agency. Compliance with legal obligations is essential for maintaining the integrity of our Service and protecting our users' rights. By adhering to legal requirements, we can ensure that our operations remain lawful and transparent.
      </li>
      <li>
        <strong>With Your Consent:</strong> We may share your information with third parties if you give us your consent to do so. Your explicit consent ensures that you have control over how your information is shared and used. By seeking your consent, we respect your preferences and ensure that your information is handled in accordance with your wishes.
      </li>
    </ul>

    <h3 id="choices" style={styles.h3}>6. Your Choices - Opting Out, Correcting, or Accessing Your Information</h3>
    <p style={styles.p}>You have the right to:</p>

    <ul style={styles.ul}>
      <li>
        <strong>Opt-Out:</strong> You can opt out of receiving promotional emails from us by following the unsubscribe instructions in those emails. Opting out of promotional communications does not affect your receipt of transactional communications related to your account or use of our Service. By allowing you to opt out, we respect your preferences while ensuring that you continue to receive essential information about your account.
      </li>
      <li>
        <strong>Access, Update, or Correct Information:</strong> You can access, update, or correct your personal information by logging into your account or contacting us directly. Keeping your information accurate and up to date is important for maintaining the quality and effectiveness of our Service. By providing you with the ability to update your information, we ensure that you have control over your personal data and can make necessary adjustments as needed.
      </li>
      <li>
        <strong>Delete Information:</strong> You can request that we delete your personal information. Please note that some information may be retained for legal, operational, or security reasons. By allowing you to request the deletion of your information, we respect your right to privacy while ensuring that we comply with legal and operational requirements.
      </li>
    </ul>

    <p style={styles.p}>
      If you have any questions or need assistance with these rights, please contact us using the contact information provided below. We are committed to helping you exercise your rights and ensuring that your information is handled in accordance with your preferences.
    </p>

    <h3 id="security" style={styles.h3}>7. Data Security and Data Transfers</h3>
    <p style={styles.p}>We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.</p>

    <ul style={styles.ul}>
      <li>
        <strong>Security Measures:</strong> We use encryption, access controls, and secure servers to safeguard your information. These measures are designed to protect your data from unauthorized access and ensure that it is stored securely. By implementing robust security measures, we can minimize the risk of data breaches and protect your personal information effectively.
      </li>
      <li>
        <strong>Data Transfers:</strong> Your information may be transferred to and processed in countries other than your own. These countries may have different data protection laws, but we take appropriate steps to ensure that your information receives the same level of protection as it would in your home country. By complying with international data protection standards, we can ensure that your information remains secure regardless of where it is processed.
      </li>
    </ul>

    <h3 id="dispute" style={styles.h3}>8. Dispute Resolution</h3>
    <p style={styles.p}>If you have any complaints regarding our privacy practices, please contact us. We will work with you to resolve your concerns.</p>

    <h3 id="changes" style={styles.h3}>9. Notice of Changes</h3>
    <p style={styles.p}>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on our Website and updating the "Effective Date" above. Your continued use of our Services after any changes indicates your acceptance of the updated Privacy Policy.</p>

    <h3 id="contact" style={styles.h3}>10. Contacting Namekart</h3>
    <p style={styles.p}>If you have any questions about this Privacy Policy or our privacy practices, please contact us at:</p>
    <p style={styles.p}><strong>Email:</strong> privacy@namekart.com</p>
    <p style={styles.p}><strong>Address:</strong> Namekart Private Limited, 123 Main Street, Anytown, USA</p>

    <p style={styles.p}>Thank you for using Namekart CRM. We are committed to protecting your privacy and providing you with a safe and secure experience.</p>
  </div>
);

export default PrivacyPolicy;
